import { Project } from "@/types";


export const projects: Project[] = [
      {
        title: 'Eledeck - Startup*',
        description: 'An AI-powered revision platform, for students to improve their study systems using scientifically backed study techniques. Key features include notes to flashcard generator, online Feynman chatbot, learning type classification and smart scheduling system.',
        technologies: ['Next.js', 'PostgreSQL', 'Tailwind CSS', 'LLM', 'OCR'],
        githubLink: 'https://eledeck.com/',
        demoLink: 'https://eledeck.com/',
        image: '/projects/Eledeck.webp',
      },
      {
        title: 'DJcode to WAV compiler in C',
        description: 'Designed a custom-made esoteric programming language which when ran, will be converted into a playable WAV file.',
        technologies: ['C', 'Compilers', 'WAV', 'Sound Synthesis'],
        githubLink: 'https://github.com/jalenmateo/DJcode',
        demoLink: 'https://drive.google.com/file/d/1q8qhL1Dea4lTrw2D2wto88EiWNIOIHKX/view?usp=sharing',
        image: '/projects/DJcode.webp',
      },
      {
        title: 'ArXiV RAG for research paper retrieval',
        description: 'RAG (Retrieval-Augmented Generation) pipeline for research paper retrieval and citation-aware response generation. The pipeline combines embeddings from an ensemble retriever (FAISS and BM25) integrated within the provided arxiv_index files, enabling efficient context retrieval from research papers.',
        technologies: ['LLM', 'langchain', 'RAG', 'FAISS', 'BM25'],
        githubLink: 'https://github.com/jalenmateo/ArXiV-RAG',
        demoLink: '',
        image: '/projects/RAG_ARXIV.webp',
      },
      {
        title: 'Alpha - T3 model research',
        description: 'Utilized Python (Kwant, PythTB), Julia, and MATLAB for advanced data visualization, quantum transport simulations, and numerical computations of physics models in an alpha-T3 spintronics system. Notably published in Physical Review B',
        technologies: ['Julia', 'MATLAB', 'Quantum Physics'],
        githubLink: '',
        demoLink: 'https://www.researchgate.net/publication/382884794_Floquet_engineering_of_topological_phase_transitions_in_quantum_spin_Hall_alpha-T_3_system',
        image: '/projects/alphat3.webp',
      },
      {
        title: 'Reaction Wheel Backpack for Fall Prevention',
        description: 'Designed and prototyped a reaction wheel backpack to minimise falls in one axis of movement. Complete with fall detection algorithm development and custom PCB design for the electronics.',
        technologies: ['PCB design', 'CAD', 'C', 'C++'],
        githubLink: '',
        demoLink: 'https://drive.google.com/file/d/1rRdoOcSAh9nKCumwrXxQB3I2xlgVcgj5/view?usp=sharing',
        image: '/projects/RxnWheel.webp',
      },
      {
        title: 'Chaos Theory for PRNG in FPGA',
        description: 'Developed an algorithm in C for a Pseudo Random Number Generator (PRNG) in FPGA applications. This project involved using logistic maps and manipulation to be able to properly display a random number on a physical 7 segment display. Notably published in IEEE:	arXiv:2404.19246',
        technologies: ['C', 'Research', 'Chaos Theor', 'FPGA', 'Verilog HDL'],
        githubLink: 'https://github.com/syarifazhar/DSL-2024/tree/T04-(CMOD-A7-Group-2D)',
        demoLink: 'https://arxiv.org/abs/2404.19246#:~:text=This%20project%20develops%20a%20pseudo-random%20number%20generator%20%28PRNG%29,Theorem%20%28CLT%29%20function%20to%20achieve%20a%20Gaussian%20distribution.',
        image: '/projects/FPGACHAOS.webp',
      },
      {
        title: 'Portfolio Website',
        description: 'My personal portfolio website showcasing my projects and skills.',
        technologies: ['Next.js', 'Tailwind CSS', 'Framer Motion'],
        githubLink: 'https://github.com/jalenmateo/portfolio-website',
        demoLink: 'https://jalenmateo.com/',
        image: '/projects/Website_Pfolio.webp',
      },
      {
        title: 'Locally Hosted Feynman Chatbot For Accessible Learning',
        description: 'A small local application that can accurately score user explanations and give valid, appropriate prompts for the user to further their understanding of a concept. Complete with finetuned Qwen LLM and finetuned BERT models.',
        technologies: ['Python', 'LLM'],
        githubLink: '',
        demoLink: 'https://drive.google.com/file/d/166aM4IH_-apqzmW6YaER9-8kdneqKxgi/view?usp=sharing',
        image: '/projects/FeynmanChat.webp',
      },
      {
        title: 'Designing a Current Starved Ring Oscillator',
        description: 'Utilised Cadence to design and simulate the response of a custom current starved ring oscillator. The custom design ensured a small footprint while passing all EDC.',
        technologies: ['Cadence'],
        githubLink: 'https://github.com',
        demoLink: 'https://demo.com',
        image: '/projects/CRSO_DDIC.webp',
      },
      {
        title: 'KSEC 2023 and RoboClash 2022/2023',
        description: 'Designed and developed multiple robots capable of autonomous movement and other functionalities. Clinched 3rd in multiple occasions.',
        technologies: ['CAD', 'PCB Design', 'Robotics', 'Prototyping'],
        githubLink: '',
        demoLink: '',
        image: '/projects/mechnuggetss.jpg',
      },
      {
        title: 'Wifi Harvesting for Wireless Sensor Systems',
        description: 'Developed a system to harvest ambient WiFi energy to power ultra-low-power sensor systems. Includes rectenna design and signal conditioning circuits.',
        technologies: ['RF Systems', 'PCB', 'CAD'],
        githubLink: '',
        demoLink: '',
        image: '/projects/WIFIHARVESTING.webp',
      },
      {
        title: 'Eavesdropping Using Lasers',
        description: 'Built a prototype to demonstrate laser microphone eavesdropping techniques, where sound vibrations on surfaces are detected and reconstructed using photodiodes and laser reflection.',
        technologies: ['Analog Electronics', 'Optics'],
        githubLink: '',
        demoLink: '',
        image: '/projects/LASER.webp',
      },
      {
        title: 'Covid-19 Spread Modelling with SIR variants',
        description: 'Simulated the spread of COVID-19 using standard and extended SIR models, including quarantine and lockdown parameters, to evaluate intervention impacts. Accurately modelled Singapores Covid outcomes.',
        technologies: ['Python', 'Mathematical Modelling'],
        githubLink: '',
        demoLink: '',
        image: '/projects/COVID.webp',
      },
      {
        title: 'Solar Powered Food Dehydrator',
        description: 'Designed and tested a low-cost, solar-powered food dehydrator for sustainable food preservation in low-resource areas.',
        technologies: ['CAD', 'Electronics'],
        githubLink: '',
        demoLink: '',
        image: '/projects/dehydrator.webp',
      },
      {
        title: 'Improving a Peltier-Based Desktop Cooler',
        description: 'Redesigned thermal insulation and fan systems of a small Peltier desktop cooler, improving energy efficiency and cooling effectiveness.',
        technologies: ['Thermal Systems', 'Electronics'],
        githubLink: '',
        demoLink: '',
        image: '/projects/PeltierCooler.webp',
      },
      {
        title: 'Chaos In Coupled Logistic Maps',
        description: 'A research project looking into the results of different types and strengths of coupling for Logistic Maps.',
        technologies: ['Julia', 'MatLab'],
        githubLink: '',
        demoLink: '',
        image: '/projects/CoupledLOGMAPS.webp',
      },
      {
        title: 'Educational Dice Game',
        description: 'Designed an educational dice game for children to intuitively grasp basic arithmetic concepts through interactive play and physical engagement.',
        technologies: ['TKinter', 'Python'],
        githubLink: '',
        demoLink: 'https://drive.google.com/file/d/14pw2bz1SMRI8OGcjyqmiacs26oiz29jB/view?usp=sharing',
        image: '/projects/DICE_GAME.webp',
      },
      {
        title: 'Fixing Up Old 3D Printers',
        description: 'Refurbished and optimized several second-hand 3D printers, including firmware tuning, mechanical realignment, and custom part replacements.',
        technologies: ['3D Printing', 'Hardware Repair'],
        githubLink: '',
        demoLink: '',
        image: '/projects/3Dprinters.webp',
      },
      {
        title: 'Interactive Gazebo',
        description: 'Designed smart gazebos with embedded sensors and interactivity features such as motion-activated lighting and dynamic sound playback.',
        technologies: ['Arduino', 'Sensor Integration', 'C', 'Electronics'],
        githubLink: '',
        demoLink: 'https://drive.google.com/file/d/1EzO3OnTt02-mkjQRJqnCF6Bli7Kpt9cR/view?usp=sharing',
        image: '/projects/GAZEBO.webp',
      },
      {
        title: 'Mars Surface Modelling and Parachute Simulation',
        description: 'Simulated Mars terrain descent and parachute deployment dynamics using MATLAB and physics-based models to inform design of descent systems for thin-atmosphere conditions.',
        technologies: ['Rhino CAD', 'Simulation'],
        githubLink: '',
        demoLink: '',
        image: '/projects/Mars_SIM.webp',
      },
      {
        title: 'Metal Detector',
        description: 'Built a functioning metal detector using tuned LC circuits and signal amplification. Project emphasized sensitivity tuning and analog circuit design.',
        technologies: ['Analog Electronics', 'Inductive Sensing'],
        githubLink: '',
        demoLink: '',
        image: '/projects/metal_detector.webp',
      },
      {
        title: 'Exploring Topological Properties of Graphene',
        description: 'Investigated topological band structure and edge state behavior in graphene and related 2D materials using Python simulation tools and tight-binding models.',
        technologies: ['Python', 'Quantum Materials', 'Physics'],
        githubLink: '',
        demoLink: '',
        image: '/projects/graphene.webp',
      },
      {
        title: 'Convex Geometry Proofs',
        description: 'Explored and presented key results in convex geometry, with accompanying visualizations and proofs.',
        technologies: ['Mathematics', 'LaTeX', 'Proof Writing'],
        githubLink: '',
        demoLink: '',
        image: '/projects/Convex_Proofs.webp',
      },
      {
        title: 'Sequence Labelling for Informal Texts',
        description: 'Built a sequence labelling pipeline to tag and structure informal or slang-laden text using BERT and LSTM models. Focus on text normalization and understanding.',
        technologies: ['NLP', 'BERT', 'LSTM', 'Sequence Labelling'],
        githubLink: '',
        demoLink: '',
        image: '/projects/ML_PROJ.webp',
      },
      {
        title: 'Reward Database System for Social Media App',
        description: 'Created a backend architecture for a scalable reward system integrated into a social app, supporting redemptions, point accumulation, and fraud prevention.',
        technologies: ['SQL', 'Backend', 'System Design'],
        githubLink: '',
        demoLink: '',
        image: '/projects/Algo.webp',
      },
      {
        title: 'Step Down & Boost Converter Design',
        description: 'Designed and tested a dual-mode buck-boost converter for high current systems, ensuring stable voltage regulation and thermal performance.',
        technologies: ['Power Electronics', 'LTSpice', 'Circuit Design'],
        githubLink: '',
        demoLink: '',
        image: '/projects/powahe.webp',
      },
      {
        title: 'Math Mental Card Game',
        description: 'Made a simple math game that relies on mental calculations using the given cards drawn at random.',
        technologies: ['CSS', 'JS', 'HTML'],
        githubLink: '',
        demoLink: 'https://codepen.io/Otaku-9Gagger/full/rNEmyqj',
        image: '/projects/CardGameMath.png',
      }

  ];
